#!/usr/bin/env python3

import sys
import os
from subprocess import Popen, PIPE

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, dirname+'/../lib/')
from ports import open_ports

if open_ports(sys.argv[2], 123, 'udp') == False:
    print("OK")
    print("NTP port on UDP is not open")
    sys.exit(0)

retValue = subprocess.call([dirname+'/main.sh', sys.argv[1], sys.argv[2], sys.argv[3]])
sys.exit(retValue)
