#!/usr/bin/env python3

import sys
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, dirname+'/../lib/')
from ports import open_ports

try:
    if not (open_ports(sys.argv[2], 22, 'tcp')):
        print('OK')
        print('SSH port is not open')
        sys.exit(0)
except Exception:
    print("SKIPPED")
    print("Skipped due to fail to read nmap result.")
    sys.exit(0)

with open(sys.argv[2]+'/ssh_auth.stdout', 'r') as f:
    f = f.readline()
    if f == 'OK\n':
        print('OK')
        print('SSH doesnt allow password authentication')
        sys.exit(0)
    
retValue = subprocess.call([dirname+'/main.sh', sys.argv[1], sys.argv[2], sys.argv[3]])
sys.exit(retValue)
